### ISSUE TITLE
ubuntu 22.04, 0.2.0 binary Bulid from Releases:  Grab Error: IoError

### ISSUE THREAD

**Issue by revast** [jersou/mouse-actions#1]
Hi, thanks for making this application, higly appreciated !

I made
```
sudo usermod -a -G plugdev $USER
sudo usermod -a -G input $USER
```

I get this message when I try to start it. 

```
./mouse_actions
[2023-04-06T15:42:04Z ERROR mouse_actions] Grab Error: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

**Comment by revast** [comment]
hmm.. I restarted the whole machine....

```
$ groups
dialout cdrom sudo audio video plugdev crontab sambashare input wheel 
```
still to no avail... I will try to build from source...

also , the [0.2.0](https://github.com/jersou/mouse-actions/releases/download/v0.2.0/mouse_actions_v0.2.0_Linux.tar.gz) with -V gives

```
$ ./mouse_actions -V
mouse_actions 0.1.0
```
is that a bug?


I also tried running as root:
```
$ sudo ./mouse_actions







[2023-04-06T20:22:11Z ERROR mouse_actions] Grab Error: IoError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })
```

**Comment by jersou** [comment]
I was able to reproduce the bug on a fresh VM, I will investigate.

Thanks for having reported this bug.

**Comment by jersou** [comment]
I release the v0.3.0 : it doesn't fix this bug, but it adds trace to debug the grab error...

In my Ubuntu 22.04 VM, this work as root only for now.

**Comment by jersou** [comment]
I update the doc, the user permission is required on `/dev/uinput` see below...

It's the same bug for Solaar and Steam :
* https://github.com/pwr-Solaar/Solaar/pull/1607
* https://github.com/ValveSoftware/steam-for-linux/issues/4794

I update the requirements :

To use the main feature "grab event", you need to have the read&write permission
on /dev/input/event*. Check the group of `/dev/input/event*` files :

```bash
ls -al /dev/input/event*
# > crw-rw---- 1 root input /dev/input/event5
#                     ^^^^^
```

You need to add the current user to this group, usually `input` or `plugdev` :

```bash
sudo usermod -a -G plugdev $USER
# or
sudo usermod -a -G input $USER
```

Furthermore, you must have the R/W right on /dev/uinput, you can check with:

```bash
getfacl /dev/uinput
# ...
# user:<the current user>:rw-
# ...
```

If this permission is not available on the user, to add it
temporary : `sudo setfacl -m u:$USER:rw /dev/uinput` or persistent :

```bash
sudo tee /etc/udev/rules.d/80-mouse-actions.rules <<<'KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=uinput"'
```

You need to restart your desktop session to apply these changes.

To check the user groups:

```bash
$ groups
... plugdev ... input ...
```

I release the v0.3.1 that print a better error message (and change the config format json compared to v0.2.0)

**Comment by xianghongai** [comment]
```
➜  sudo ./mouse-actions -c ~/.config/mouse-actions.json
[2024-02-13T10:52:03Z INFO  mouse_actions::config] Watch the config "/home/<user>/.config/mouse-actions.json" !
root_loop
[2024-02-13T10:52:09Z INFO  mouse_actions::process_event]      → cmd ["xdotool", "key", "ctrl+w"]
[2024-02-13T10:52:14Z ERROR mouse_actions::process_args] Grab Error: IoError(
        Os {
            code: 4,
            kind: Interrupted,
            message: "Interrupted system call",
        },
    )

```

- `echo $XDG_SESSION_TYPE`: `x11`
- `cat /etc/*release`: `PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"`
- `groups`: `<user> cdrom floppy audio dip video plugdev users input netdev bluetooth lpadmin scanner`
- `./mouse-actions -v`: `0.4.4-f2a062e (2023-07-06)`
