### ISSUE TITLE
Grab Error when trying to start to listen for gestures

### ISSUE THREAD

**Issue by KUKARAF** [jersou/mouse-actions#10]
I tried to run the elf executable downloaded from the releases in the terminal. 

I am running nobara linux on a surface book 2 with the surface-linux kernel patch 
```
[2023-06-30T09:11:34Z ERROR mouse_actions::process_args] Grab Error: IoError(
        Os {
            code: 22,
            kind: InvalidInput,
            message: "Invalid argument",
        },
    )

```

**Comment by jersou** [comment]
do you apply the requirements ? https://github.com/jersou/mouse-actions#requirement-

can you share your config ?
