### ISSUE TITLE
Grab Error: IoError

### ISSUE THREAD

**Issue by Calab** [jersou/mouse-actions#36]
Running Linux Mint Cinnamon 21.3 with 6.5.0-26-generic kernel. When I have mouse-actions-gui running and try to do my first gesture (drag to the left with my right mouse button to perform the keystroke Alt+Left) the following occurs and no more gestures are detected:

```
[2024-03-19T23:11:59Z INFO  mouse_actions::config] Watch the config "/home/steve/.config/mouse-actions.json" !
root_loop
[2024-03-19T23:12:02Z INFO  mouse_actions::process_event]      → cmd ["Alt+Left"]
[2024-03-19T23:12:05Z ERROR mouse_actions::process_args] Grab Error: IoError(
        Os {
            code: 4,
            kind: Interrupted,
            message: "Interrupted system call",
        },
    )
```

I believe that I have met all the requirements listed. Any idea why it doesn't work? What do you need to help troubleshoot this?

**Comment by Calab** [comment]
In debug mode I see the following line in the output when I try to use a gesture.

`2024-03-20T00:46:06Z TRACE mouse_actions::process_event] spawn result : Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })`

**Comment by calendulish** [comment]
> In trace mode I see the following line in the output when I try to use a gesture.
> 
> `2024-03-20T00:46:06Z TRACE mouse_actions::process_event] spawn result : Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })`
> 
> Do you know what file it is looking for?

it's the file you configured as command in your gesture config

**Comment by Calab** [comment]
Just to follow up...

I was trying to bind mouse strokes to key strokes.

My solution was to install EasyStroke instead.

**Comment by jersou** [comment]
The command part is to specify a command to be executed - a shell command ! - e.g., `xdotool key alt+Left`
