### ISSUE TITLE
GUI window is blank

### ISSUE THREAD

**Issue by Goosegit11** [jersou/mouse-actions#38]
![image](https://github.com/jersou/mouse-actions/assets/89806596/9b85223e-76eb-41d2-abae-701f2233bf8a)

`AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer`

```sh

% mouse-actions-gui
    no_listen: false,
    config_path: None,
    command: None,
    version: false,
    log_level: None,
}

** (mouse-actions-gui:453380): WARNING **: 18:10:04.619: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

```

**Comment by larvanitis** [comment]
No idea what the cause is but I found this on the Internets...

In the command line run: `WEBKIT_DISABLE_DMABUF_RENDERER=1 mouse-actions-gui`

**Comment by Goosegit11** [comment]
That works

**Comment by jersou** [comment]
Thanks for the workaround `WEBKIT_DISABLE_DMABUF_RENDERER=1` 
It was referenced in this issue https://github.com/tauri-apps/tauri/issues/9304
I will add it to the readme
