### ISSUE TITLE
Rust 1.80.0 will break mouse-actions

### ISSUE THREAD

**Issue by rgri** [jersou/mouse-actions#47]
Hi, beginning with Rust 1.80.0, mouse-actions will fail to build due to a breakage which I believe only affects the dependency `time`, which itself is a dependency of `vergen`. See some more details [here](https://github.com/NixOS/nixpkgs/issues/332957#issue-2453023525).

I maintain `mouse-actions` on the repository [nixpkgs](https://github.com/NixOS/nixpkgs), and would like to help fix this. The package builds successfully using rust 1.80.0 on both of these commits on my fork of mouse-actions:

- [a981b38](https://github.com/rgri/mouse-actions/commit/a981b38846e6bf5fd348be5d93ab9d2ca79c9342) (only bumping time)
- [922acc5](https://github.com/rgri/mouse-actions/commit/922acc523aff8c720e7185e7f03a61b9091d9ea1) (bumping vergen)

Please let me know what, if any, version bumps you would like and I can make a PR.

**Comment by jersou** [comment]
Thanks ! I've updated the dependencies, and it now builds in Rust 1.80.
I will release this version

**Comment by rgri** [comment]
`v0.4.5` builds with rust 1.80.0 on the latest `nixpkgs-staging-next`. Closing as resolved.
